### ISSUE TITLE
PSR-4 autoloading convention

### ISSUE THREAD

**Issue by fsti-francohora** [loyaltycorp/easy-monorepo#21]
**Describe the bug**
Encountered the bug on EasyApiToken due to the filenames are not the same with there corresponding classname.

**To Reproduce**
I include the the package to the project and it displays a `EasyApiTokenDecoderInterface` does not exist

**Expected behavior**
File must be autoload properly by the composer

**Additional context**

**Comment by natepage** [comment]
PR merged, thank you for your help.
